### ISSUE TITLE
python3-lttnganalyses does not exist in ppt

### ISSUE THREAD

**Issue by vchekan** [lttng/lttng-analyses#26]
I have set Ubuntu ppt as described on github README.rst but ```python3-lttnganalyses``` can not be found. All other packages installed just fine. 

OS: ```Linux Mint 17.3 Rosa```
uname -a: ```Linux desktop 3.18.5-031805-generic #201501292218 SMP Fri Jan 30 03:19:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by abusque** [comment]
Hi, thanks for reporting. I'm actually not sure this package has ever been in the PPA as indicated in the README. I'll have to check with @mjeanson who usually takes care of the packaging part to fix this. In the meantime, you can install using `pip` (or `pip3` if your default python install is not python 3) as described in the README, or simply run or install from source.

**Comment by mjeanson** [comment]
The python3-lttnganalyses package was added to all PPAs for precise and trusty.
