### ISSUE TITLE
Dependency on 'babeltrace' binary is not enforced

### ISSUE THREAD

**Issue by alexmonthy** [lttng/lttng-analyses#49]
I installed the analyses using `sudo ./setup.py install` on a system with the python3-babeltrace package, but not the `babeltrace` binary itself. No error was reported on installation.

Running for example the `lttng-cputop-mi --metadata` command works, but running the actual analysis does not, and the following message is printed:

    Error: Cannot open trace: [Errno 2] No such file or directory: 'babeltrace'

**Comment by abusque** [comment]
I'll add the dependency check at installation, thanks for reporting.

Ideally, in the long-run, one should only need the bindings and not the actual executable, as it's currently only being used as a workaround for limitations in the API exposed through the bindings.
