### ISSUE TITLE
option --freq-series is not honored in lttng-schedfreq

### ISSUE THREAD

**Issue by compudj** [lttng/lttng-analyses#83]
We would expect lttng-schedfreq to combine all pids into a single table (or all priorities if --per-prio is specified) giving multi-series, but it currently does not (tested stable-0.4 and master). It keeps outputting multiple tables (one per pid, or one per priority).

The feature seems to work fine with lttng-irqfreq, but not lttng-schedfreq.

**Comment by jdesfossez** [comment]
This has been fixed by commit cdf1fb350844e1ca188344c455f747733431f916
